config/routes.rb
Rails.application.routes.draw do

  mount CurrentUser::Engine => '/current_user'

  root 'schedules#index'

  get 'holidays/feed' => 'holidays#feed', defaults: { format: 'json' }
  get 'swap_requests/feed' => 'swap_requests#feed', defaults: { format: 'json' }

  resources :conflicts, only: [:create] do
    collection do
      get 'feed', defaults: { format: 'json' }
    end
  end

  resources :schedules, only: [:index] do
    collection do
      get 'feed', defaults: { format: 'json' }
      delete 'clear'
      post :set_schedule
    end
  end

  resources :swap_requests, only: [:create, :update], defaults: { format: 'json' }

  get 'employee/dates' => 'employees#scheduled_dates'
  get 'employee/current_hero' => 'employees#current_hero'

  get 'schedules/:employee_id' => 'schedules#index'

  get 'signed_in' => 'application#signed_in'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base

  include DateValidations
  require 'amb'

  scope :current, -> { where("support_date >= ?", Date.today) }

  belongs_to :employee
  has_many :outgoing_swap_requests, foreign_key: :source_id,
                                  class_name: SwapRequest, dependent: :destroy
  has_many :incoming_swap_requests, foreign_key: :target_id,
                                  class_name: SwapRequest, dependent: :destroy

  validates_presence_of :employee

  validates :support_date, date: true
  validates_uniqueness_of :support_date
  validate :support_date_is_workday
  validate :employee_available

  def self.from_list(employee_list)
    employee_list.each do |employee_name|
      employee = Employee.find_or_create_by(name: employee_name)
      schedule = self.create( employee: employee,
                              support_date: SupportDate.next_open_day)
      puts schedule.errors.full_messages
    end
  end

  def self.reschedule(conflict)
    current_schedule = self.current.includes(:employee).all

    new_schedule = self.generate_new_schedule(conflict, current_schedule)

    # retry in reverse order in case conflict is last date
    if new_schedule.empty?
      new_schedule = self.generate_new_schedule(conflict,
        current_schedule.reverse)
    end

    self.replace_schedule(current_schedule, new_schedule) if new_schedule.any?
  end

  private

  def self.generate_new_schedule(conflict, current_schedule)
    schedules = {}
    begin
      current_schedule.map(&:employee).each do |e|
        date = Amb.choose( *current_schedule.map(&:support_date) )
        Amb.assert( !e.conflicts.where(support_date: date ).exists? )
        Amb.assert( !( conflict.support_date == date &&
                       conflict.employee_id == e.id ) )
        Amb.assert !schedules.has_key?(date)
        schedules[date] = Schedule.new(employee: e, support_date: date)
      end
    rescue Exception => e
      schedules = {}
    end

    schedules.values
  end

  def self.replace_schedule(current_schedule, new_schedule)
    Schedule.transaction do
      current_schedule.destroy_all
      new_schedule.each(&:save!)
    end
    true
  rescue Exception => e
    false
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  include SchedulesControllable

  require 'csv'

  respond_to :json

  def index
    todays_schedule = Schedule.find_by(support_date: Date.today )
    @current_hero = todays_schedule ? todays_schedule.employee.name : nil
  end

  def feed
    schedules = feed_base(Schedule).joins(:employee).select([
        "#{Schedule.table_name}.*",
        "'schedule'::character(8) AS event_type",
        "#{Employee.table_name}.name",
        "#{Employee.table_name}.id AS employee_id"
      ])

    if params[:employee_id].present?
      schedules = schedules.where(employee_id: params[:employee_id])
    end
    respond_with schedules
  end

  def set_schedule
    file = params[:schedule][:file]
    list = CSV.read(file.tempfile.path).flatten
    Schedule.from_list(list)
  rescue Exception => e
    flash[:notice] = "There was a problem creating the schedule. " +
                     "Please try again."
  ensure
    redirect_to root_url
  end

  def clear
    Employee.destroy_all
    redirect_to root_url
  end

end

app/views/schedules/_header.html.haml
.top-nav
  %div
    - if @current_hero
      Today's support hero is:
      %span.current-hero= @current_hero
    - else
      No one is on duty today

  %div
    = label_tag 'employee', 'View Schedule For:'
    = select_tag(:employee, options_from_collection_for_select(Employee.all,
                              "id", "name", params[:employee_id]),
                              { :include_blank => "Everyone" } )

  %div
    = link_to "Clear Schedule", clear_schedules_path, { method: :delete,
        data: { :confirm => "Are you sure you would like to clear the schedule?" } }

  %div
    = link_to "Load Schedule", nil, { :id => "schedule_load_link" }

  %div
    - if current_user
      Logged in as:
      = current_user.name
      = link_to "Logout",
        "#{current_user_path}/#{::CurrentUser.authentication_key}/sign_in"
    - else
      = link_to "Sign In",
        "#{current_user_path}/#{::CurrentUser.authentication_key}/sign_in"

%div
  %hr

app/views/schedules/_schedule_load_form.html.haml
%div#schedule_load_form{ :title => "Create Schedule" }
  %p
    Create a schedule from a text file list of employees.
  =form_tag set_schedule_schedules_path, method: :post, multipart: true do
    =file_field(:schedule, :file)

app/views/schedules/_schedule_swap_form.html.haml
- if current_user
  %div#schedule_swap_form{ :title => "Swap Scheduled Days" }
    %p
      Request to be support hero on:
      %span.swap-date

    =form_tag swap_requests_path, method: :post, multipart: true, remote: true do
      = hidden_field_tag :target_schedule_id
      = label :schedule, "instead of:"
      = select_tag :src_schedule_id

app/views/schedules/index.html.haml
= render :partial => "header"

#calendar

= render :partial => "schedule_load_form"

= render :partial => "schedule_swap_form"